config/routes.rb
Rails.application.routes.draw do
	draw(:devise)
	draw(:home)
	draw(:import)
	draw(:source)
	draw(:source_type)

	# Default homepage
	root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
	self.abstract_class = true
end

app/models/factories/chase_visa_transaction_factory.rb
require 'csv'
require 'digest'

class ChaseVisaTransactionFactory

	def build_all(csv_file, user, transaction_source)

		# Sort all transactions by transaction date
		transaction_hashes = parse_csv(csv_file)

		# Add user and source information to each transaction hash
		add_user_id_source_id_and_timestamps_to_each_transaction_hash(transaction_hashes, user, transaction_source)

		# TODO: VALIDATE THE CORRECTNESS OF EACH TRANSACTION

		transaction_hashes
	end

	private

	def parse_csv(csv_file)
		csv_parser = CSV.read(csv_file, headers: true)

		# Sort by transaction_date.
		# This order matters since it dictates what the generated transaction_id is
		csv_parser = sort_csv_file_by_transaction_date(csv_parser)

		previous_month = {}

		transaction_hashes = []
		csv_parser.each_with_index do |row, transaction_index_in_file|
			# For now, we're ignoring the post_date
			transaction_date = Date.strptime(row[TRANSACTION_DATE], "%m/%d/%Y")
			post_date = Date.strptime(row[POST_DATE], "%m/%d/%Y")

			# Credit/Debit currency amount
			amount = row[AMOUNT]

			# Vendor properties
			description = row[DESCRIPTION]
			category = row[CATEGORY]

			# Sale/Credit/Adjustment:
			transaction_type = row[TYPE].downcase.to_s

			# Reset the month index counter if we've found a new month
			previous_month = update_current_month_index_hash(previous_month, transaction_date, transaction_index_in_file)

			# TransactionId
			transaction_id = generate_transaction_id(transaction_index_in_file - previous_month[:start_index], transaction_date, transaction_type, amount, description)

			# Create a transaction hash.  We're doing this so we can use ActiveRecord::upsert_all
			transaction_hashes << {
				name: description,
				# date: Date.strptime(transaction_date, "%m/%d/%Y"),
				date: transaction_date,
				transaction_type: Transaction.transaction_types[transaction_type],
				amount: amount,
				transaction_category: category,
				transaction_id: transaction_id
			}
		end

		transaction_hashes
	end

	def sort_csv_file_by_transaction_date(csv_parser)
		# Sort by transaction_date.
		# This order matters since it dictates what the generated transaction_id is
		csv_parser.sort do |lhs, rhs|
			Date.strptime(lhs[TRANSACTION_DATE], "%m/%d/%Y") <=> Date.strptime(rhs[TRANSACTION_DATE], "%m/%d/%Y")
		end
	end

	def update_current_month_index_hash(current_month_index_hash, transaction_date, transaction_index)
		current_date = current_month_index_hash[:current_month]

		if current_date.nil?
			# We're on the first index
			current_month_index_hash[:current_month] = transaction_date
			current_month_index_hash[:start_index] = transaction_index
		elsif current_date.year < transaction_date.year or current_date.month < transaction_date.month
			current_month_index_hash[:current_month] = transaction_date
			current_month_index_hash[:start_index] = transaction_index
		end

		current_month_index_hash
	end

	# TODO: TAKE IN A LIST OF TRANSACTION OBJECTS INSTEAD
	# TODO: MOVE TO ITS OWN CLASS
	def generate_transaction_id(record_index, transaction_date, transaction_type, transaction_amount, transaction_name)

		hash_string = {
			year: transaction_date.year,
			month: transaction_date.month,
			day: transaction_date.day,
			record_index: record_index,
			type: transaction_type,
			amount: transaction_amount,
			name: transaction_name
		}.to_s

		Digest::MD5.hexdigest(hash_string)
	end

	def add_user_id_source_id_and_timestamps_to_each_transaction_hash(transaction_hashes, user, source)
		now = Time.now

		transaction_hashes.each do |transaction|
			transaction[:user_id] = user.id
			transaction[:source_id] = source.id
			transaction[:created_at] = now
			transaction[:updated_at] = now
		end

		transaction_hashes
	end

	TRANSACTION_DATE = 'Transaction Date'
	POST_DATE = 'Post Date'
	DESCRIPTION = 'Description'
	CATEGORY = 'Category'
	TYPE = 'Type'
	AMOUNT = 'Amount'

end

app/models/factories/factory_library.rb
require 'chase_visa_transaction_factory'

class FactoryLibrary

	def find_factory(source)
		ChaseVisaTransactionFactory.new
	end

end

app/models/servicer.rb
class Servicer < ApplicationRecord
	belongs_to :source_type
	belongs_to :user
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :user
  belongs_to :servicer
end

app/models/source_type.rb
class SourceType < ApplicationRecord
	belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
	belongs_to :user
	belongs_to :source

	enum transaction_type: [:sale, :return, :payment, :fee, :adjustment]
end

app/models/user.rb
class User < ApplicationRecord

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

end

app/controllers/import_controller.rb
require 'source_queries'
require 'factories/factory_library'

class ImportController < ApplicationController
	before_action :authenticate_user!

	def index
		@sources = SourceQueries.new(current_user).all
	end

	def upload_transactions
		records = params[:records]
		source_id = params[:source_id]

		source = Source.find(source_id)
		transaction_factory = FactoryLibrary.new.find_factory(source)
		transactions = transaction_factory.build_all(records, current_user, source)

		Transaction.upsert_all(transactions)
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:name, :email, :password)
	end

	def account_update_params
		params.require(:user).permit(:name, :email, :password)
	end

end

app/controllers/sources_controller.rb
require 'servicer_queries'
require 'source_queries'
require 'source_type_queries'

class SourcesController < ApplicationController
	before_action :authenticate_user!

	def index
		user = current_user

		@new_source_type = SourceType.new(user: user)
		@new_servicer = Servicer.new(user: user)
		@new_source = Source.new(user: user)

		@source_types = SourceTypeQueries.new(user).all
		@servicers = ServicerQueries.new(user).all
		@sources = SourceQueries.new(user).all
	end

	def new_source_type
		user = current_user
		@source_type = SourceType.new(new_source_type_params)
		@source_type.user = user

		if @source_type.save
			@source_types = SourceTypeQueries.new(user).all
			redirect_to action: :index
		else
			render json: @source_type.errors, status: :unprocessable_entity
		end
	end

	def new_source_type_params
		params.require(:source_type).permit(:name)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

	def links

		if user_signed_in?
			'home/partials/nav/dropdown'
		else
			'home/partials/nav/auth_links'
		end
	end

end

app/helpers/import_helper.rb
module ImportHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/home/index.html.erb
<%= render 'home/partials/nav' %>

<%= render 'home/partials/header' %>

app/views/home/partials/_header.html.erb
<div class="jumbotron jumbotron-fluid mb-0">

  <div class="container">

    <h1 class="display-4 text-white">Visualize your personal finances today</h1>

    <p class="lead mb-5">Dominate your cash flow.</p>

  </div>

</div>

app/views/home/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'Mammon', home_index_path, class: 'navbar-brand mx-3' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" datatarget="#navbarSupportedContent" aria-controls="navbarSupportedContent" ariaexpanded="false" aria-label="Toggle navigation">
      <span class="toggler"><i class="fas fa-bars text-white"></i></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <%= render links %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/partials/nav/_auth_links.html.erb
<li class="nav-item">
  <%= link_to 'Sign Up', register_path, class: 'nav-link signup-btn btn btnsuccess py-1 mx-3', data: { turbolinks: false } %>
</li>
<li class="nav-item">
  <%= link_to 'Log In', login_path, class: 'nav-link mx-3' %>
</li>

app/views/home/partials/nav/_dropdown.html.erb
<li class="nav-item">
  <%= link_to 'Dashboard', home_index_path, class: 'nav-link mx-3' %>
</li>

<li class="nav-item">
  <%= link_to 'Import', import_index_path, class: 'nav-link mx-3' %>
</li>

<li class="nav-item">
  <%= link_to 'Sources', sources_index_path, class: 'nav-link mx-3' %>
</li>

<li class="nav-item dropdown">
  <a class="nav-link mx-3 dropdown-toggle" href="#" id="navbarDropdown"
     role="button" data-toggle="dropdown"
     aria-haspopup="true" aria-expanded="false">
    <%= current_user.name %>
  </a>

  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <%= link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item', method: :get %>
    <%= link_to 'Logout', logout_path, class: 'dropdown-item', method: :delete %>
  </div>

</li>

app/views/import/index.html.erb
<%= render 'home/partials/nav' %>


<html>
  <head>
    <title>Import</title>
    <%#= javascript_pack_tag 'import' %>
  </head>
  <body>
    <div class="container">

      <div class="row border-bottom" id="header">
        <h1>Import transactions</h1>
      </div>

      <div class="row" id="upload-transaction-form">

        <%= form_with url: 'upload_transactions', multipart: true do |f| %>

          <div class="form-group">
            <div class="input-group mb-3">
              <label for="records">Source</label>
              <%= f.collection_select(:source_id, @sources, :id, :name, { class: 'selectpicker form-control', prompt: true }) %>
            </div>

            <div class="form-group mb-3">
              <!-- onchange: 'file_field_input_changed(this)'-->
              <%= f.file_field(:records) %>
            </div>

            <div class="form-group mb-3">
              <%= f.submit "Import" %>
            </div>

          </div>

        <% end %>

      </div>

    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mammon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fontawesome/5.11.2/css/all.min.css">
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/sources/index.html.erb
<%= render 'home/partials/nav' %>

<html>
  <head>
    <title>Sources</title>
    <%#= javascript_pack_tag 'sources' %>
  </head>
  <body>
    <div class="container">
      <div class="row border-bottom" id="header">
        <h1>Sources types</h1>
        <button type="button" id="add-button" class="btn btn-default" data-toggle="modal" data-target="#addSourceTypeModal">Add</button>
      </div>
      <div class="row">
        <%= render partial: 'sources/partials/table', locals: { items: @source_types } %>
      </div>

      <div class="row border-bottom" id="header">
        <h1>Servicers</h1>
        <button type="button" id="add-button" class="btn btn-default" data-toggle="modal" data-target="#addSourceTypeModal">Add</button>
      </div>
      <div class="row">
        <%= render partial: 'sources/partials/table', locals: { items: @servicers } %>
      </div>

      <div class="row border-bottom" id="header">
        <h1>Source</h1>
        <button type="button" id="add-button" class="btn btn-default" data-toggle="modal" data-target="#addSourceTypeModal">Add</button>
      </div>
      <div class="row">
        <%= render partial: 'sources/partials/table', locals: { items: @sources } %>
      </div>

    </div>
  </body>
</html>

<!-- add source type modal -->
<div class="modal" id="addSourceTypeModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <%= form_with model: @new_source_type do |f| %>

        <div class="modal-body form-group">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon3">Source type name</span>
            </div>
            <%= f.text_field(:name, label: 'Name', class: 'form-control') %>
          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= button_to "Save", :source_types, class: 'btn btn-primary', type: 'button' %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/sources/partials/_table.html.erb
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
    </tr>
  </thead>
  <tbody>
    <% items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>